apiVersion: v1
kind: Service
metadata:
    name: cluster-config-service
spec:
    selector:
        app: cluster-config-service
    ports:
        - name: web
          protocol: TCP
          port: 80
          targetPort: 80
